# Generated by Django 3.2.4 on 2021-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=150)),
            ],
        ),
    ]
