# Generated by Django 3.2.4 on 2021-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='title_description',
            field=models.CharField(default='', max_length=650),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
